# Define a method display_board that prints a 3x3 Tic Tac Toe Board
puts "Welcome to Tic Tac Toe"
puts "   |   |   "
puts "-----------"
puts "|   |"
puts "-----------"
puts "   |   |"
puts "What move would X like to make (1-9)?"
puts "> 5"
puts "   |   |"
puts "-----------"
puts "| X |"
puts "-----------"
puts "   |   |"
puts "What move would O like to make (1-9)?"
puts "> 1"
puts "0 |   |"
puts "-----------"
puts "   | X |"
puts "-----------"
puts "   |   |"
puts "# etc..."
